### ISSUE TITLE
ModelNotFoundException when using queue

### ISSUE THREAD

**Issue by ikudosi** [danielme85/laravel-log-to-db#1]
Hello,

I am getting this particular message when putting the log into the queue. I followed the installation guide to a T - am I missing something? Below is the stack trace. If i don't put it into the queue everything works.

`Illuminate\Database\Eloquent\ModelNotFoundException: No query results for model [danielme85\LaravelLogToDB\Models\DBLog]. in /home/vagrant/b2b/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:452
 Stack trace:
 #0 /home/vagrant/b2b/vendor/laravel/framework/src/Illuminate/Queue/SerializesAndRestoresModelIdentifiers.php(85): Illuminate\Database\Eloquent\Builder->firstOrFail()
 #1 /home/vagrant/b2b/vendor/laravel/framework/src/Illuminate/Queue/SerializesAndRestoresModelIdentifiers.php(55): danielme85\LaravelLogToDB\Jobs\SaveNewLogEvent->restoreModel(Object(Illuminate\Contracts\Database\ModelIdentifier))
 #2 /home/vagrant/b2b/vendor/laravel/framework/src/Illuminate/Queue/SerializesModels.php(45): danielme85\LaravelLogToDB\Jobs\SaveNewLogEvent->getRestoredPropertyValue(Object(Illuminate\Contracts\Database\ModelIdentifier))
 #3 [internal function]: danielme85\LaravelLogToDB\Jobs\SaveNewLogEvent->__wakeup()
 #4 /home/vagrant/b2b/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(42): unserialize('O:46:"danielme8...')
 #5 /home/vagrant/b2b/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(83): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\RedisJob), Array)
 #6 /home/vagrant/b2b/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(327): Illuminate\Queue\Jobs\Job->fire()
 #7 /home/vagrant/b2b/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(277): Illuminate\Queue\Worker->process('redis', Object(Illuminate\Queue\Jobs\RedisJob), Object(Illuminate\Queue\WorkerOptions))
 #8 /home/vagrant/b2b/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(118): Illuminate\Queue\Worker->runJob(Object(Illuminate\Queue\Jobs\RedisJob), 'redis', Object(Illuminate\Queue\WorkerOptions))
 #9 /home/vagrant/b2b/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(102): Illuminate\Queue\Worker->daemon('redis', 'default', Object(Illuminate\Queue\WorkerOptions))
 #10 /home/vagrant/b2b/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(86): Illuminate\Queue\Console\WorkCommand->runWorker('redis', 'default')
 #11 [internal function]: Illuminate\Queue\Console\WorkCommand->handle()
 #12 /home/vagrant/b2b/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
 #13 /home/vagrant/b2b/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
 #14 /home/vagrant/b2b/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
 #15 /home/vagrant/b2b/vendor/laravel/framework/src/Illuminate/Container/Container.php(572): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
 #16 /home/vagrant/b2b/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\Container\Container->call(Array)
 #17 /home/vagrant/b2b/vendor/symfony/console/Command/Command.php(255): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
 #18 /home/vagrant/b2b/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
 #19 /home/vagrant/b2b/vendor/symfony/console/Application.php(901): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
 #20 /home/vagrant/b2b/vendor/symfony/console/Application.php(262): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Queue\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
 #21 /home/vagrant/b2b/vendor/symfony/console/Application.php(145): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
 #22 /home/vagrant/b2b/vendor/laravel/framework/src/Illuminate/Console/Application.php(89): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
 #23 /home/vagrant/b2b/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
 #24 /home/vagrant/b2b/artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
 #25 {main}`

**Comment by danielme85** [comment]
Ah sorry about that: my method was flawed when passing the log object to the work queue handler, this approach never actually worked as intended. If you switch to dev-master the newest commit should fix the issue: 1bb90ec8801d37ecacf87e885caa126de8790f92

I've not had time for much "real world" testing on this, so there might be some unforeseen issues, let me know how it goes! I'l make it a minor release after some more testing if everything works.

**Comment by danielme85** [comment]
I've added some more fixes and tweaks that should solve the queue issue in this commit 375d8288eddf78f79d329407bdd46754eedc9de9
Tested working on mysql and mongodb in Homestead 7.

Thank you for reporting this issue @ikudosi 👍
