### ISSUE TITLE
 \Log::error not work

### ISSUE THREAD

**Issue by huangxingle2009** [danielme85/laravel-log-to-db#19]
![image](https://user-images.githubusercontent.com/4972859/77252872-ba4eb700-6c91-11ea-9eac-36f3e70f06ed.png)

![image](https://user-images.githubusercontent.com/4972859/77252881-c63a7900-6c91-11ea-9dea-cc851f54aae4.png)

![image](https://user-images.githubusercontent.com/4972859/77252898-df432a00-6c91-11ea-8bea-2bc93ef4f5b6.png)

it write to file, but not write to database

database log is system error,  \Log::error("something") not work

**Comment by danielme85** [comment]
Hi,
I can't recreate this issue. Seems to me like you are running into an error before that switch function is called? Also is: stack set as the LOG_CHANNEL in your .env file?


Here is a test I just did, tried to follow your example as close as I could:
<img width="681" alt="Screen Shot 2020-03-22 at 10 38 31 PM" src="https://user-images.githubusercontent.com/1576219/77275167-0b5cac00-6c8e-11ea-9077-6f4055a6f066.png">
<img width="564" alt="Screen Shot 2020-03-22 at 10 39 46 PM" src="https://user-images.githubusercontent.com/1576219/77275179-0f88c980-6c8e-11ea-9f5a-3aaea327feda.png">
<img width="618" alt="Screen Shot 2020-03-22 at 10 38 51 PM" src="https://user-images.githubusercontent.com/1576219/77275191-18799b00-6c8e-11ea-924e-7517ed6106b6.png">
<img width="868" alt="Screen Shot 2020-03-22 at 10 39 05 PM" src="https://user-images.githubusercontent.com/1576219/77275196-1b748b80-6c8e-11ea-837c-21708c4834be.png">

**Comment by huangxingle2009** [comment]
i found the question :  
php artisan queue:work  do not work 
php artisan queue:work --queue=logQueue    is work  \Log::error() can write to mysql

**Comment by danielme85** [comment]
Ah yes, I'm glad you figured it out 👍 
Let me know if you have any other questions :) 
Take care!
