### ISSUE TITLE
Observers are not working

### ISSUE THREAD

**Issue by DonSalvador** [danielme85/laravel-log-to-db#20]
The observers or the closure event of the Log model are not fired.

**Comment by danielme85** [comment]
Hi mr DonSalvador, 
so you're talking about this right..?
https://laravel.com/docs/7.x/eloquent#observers

I did manage to get a model observer to work.
\App\Providers\AppServiceProvider.php
```
namespace App\Providers;

use App\Observers\LogObserver;
use danielme85\LaravelLogToDB\LogToDB;
use Illuminate\Support\ServiceProvider;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {
        //
    }

    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        LogToDB::model()->observe(LogObserver::class);
    }
}
```

Custom observer class:
\App\Observers\LogObserver.php
```
class LogObserver
{
    /**
     * Handle the Log "created" event.
     *
     * @return void
     */
    public function created($log)
    {
        dd($log->toArray());
    }
}
```

 Log::info("hello world...");

Result: 
```
[2020-04-24 12:06:37][99] Processing: danielme85\LaravelLogToDB\Jobs\SaveNewLogEvent
array:10 [
  "message" => "hello world..."
  "level" => 200
  "level_name" => "INFO"
  "channel" => "local"
  "datetime" => "2020-04-24 12:06:27:0427"
  "extra" => array:1 [
    "memory_peak_usage" => "18 MB"
  ]
  "unix_time" => 1587744397
  "updated_at" => "2020-04-24 12:06:37"
  "created_at" => "2020-04-24 12:06:37"
  "id" => 48316
]
```

Is this what you had in mind?

**Comment by DonSalvador** [comment]
Hi @danielme85 

Yes! that work.

Not fired if I use my own model.
And I is mandatory to use the DBLog model in the observer class too.
`Argument 1 passed to App\Observers\LogObserver::created() must be an instance of App\Models\Log, instance of danielme85\LaravelLogToDB\Models\DBLog given`

Works with AppServiceProvider like you said. Thanks

**Comment by danielme85** [comment]
Oh yeah... let me look into better support for your own models. 
I think there is a better way.

**Comment by danielme85** [comment]
I added custom eloquent model support #21 , so using your own model should work better now hopefully...
https://github.com/danielme85/laravel-log-to-db#custom-eloquent-model

Please feel free to test it out with the master branch!

**Comment by danielme85** [comment]
dev-master and v2.3.x and better support for custom eloquent models now.
Thanks for pointing it out @DonSalvador
