### ISSUE TITLE
Array to string conversion on error logging

### ISSUE THREAD

**Issue by xavi7th** [danielme85/laravel-log-to-db#22]
Good day and great package. I've been using this package for a while now and it's been fabulous.

I ran into a bug and can't seem to figure out what is wrong. I am trying to log validation errors to the database. I have an ErrLog class to handle that.

`
  public function report()
  {
    ErrLog::logValidationErrors($this->validator, $this->validation_class);
  }
`

And in ErrLog I have this

`
static function logValidationErrors(Validator $validator, FormRequest $validation_class)
  {
    if (DB::transactionLevel() > 0) {
      Db::rollBack();
    }
    Log::error('hello', ['id' => 1]);
    // Log::error(get_class($validation_class) . ' validation failed.', ['data' => $validator->getData(), 'errors' => $validator->errors()->all(), get_class($validation_class) . ' validation failed.', 'context' => '']);
  }
`
The bug is this: As long as I have an array in the context parameter I get an Array to String conversion error.

If I remove the context entirely, it works, but if I supply any other parameter to context, the exception triggers a required array for parameter 2 error.

My composer file has and I have run composer update a couple of times over the past 2 days.

`"danielme85/laravel-log-to-db": "^2.3",
        "laravel/framework": "^7.0",
        "laravel/tinker": "^2.0",
        "laravel/ui": "^2.0",`

What could be wrong?

The error information is

`
danielme85\LaravelLogToDB\Models\DBLogException
Array to string conversion

vendor/danielme85/laravel-log-to-db/src/LogToDbCustomLoggingHandler.php:73

protected function write(array $record): void

  {

    if (!empty($record)) {

      if (

        !empty($record['context']['exception']) &&

        get_class($record['context']['exception']) === DBLogException::class

      ) {

        //Do nothing if empty log record or an error Exception from itself.

      } else {

        try {

          $log = new LogToDB($this->config);

          $log->newFromMonolog($record);

        } catch (DBLogException $e) {

          //do nothing if exception of self

        } catch (\Exception $e) {

          //convert any runtime Exception while logging to a special class so we can avoid our own

          //exceptions for 99% less infinite loops!

          throw new DBLogException($e->getMessage()); // This is line 73

        }

      }

    }
`

Here is a link to the flare error if necessary.

https://flareapp.io/share/J7oDNG58

Thanks again for a wonderful package

**Comment by danielme85** [comment]
This was very much a mistake on my end, I did something silly!
Thank you for bringing this to my attention @xavi7th 

This should be fixed by this commit: ada71d9bbc992276273f44299035e4c9ded5fa79
Could you try using the dev-master branch and see if that works?

You can reference it in your composer.json file like this:
`"danielme85/laravel-log-to-db": "dev-master"`
And try a composer update :)

**Comment by xavi7th** [comment]
Thank you very much for your swift reply.

I will try it out ASAP and give you a feed back

**Comment by xavi7th** [comment]
😍🥳. @danielme85 it works now.

Thank you for the work you put in.
