### ISSUE TITLE
Laravel 7: Throwable

### ISSUE THREAD

**Issue by santerref** [danielme85/laravel-log-to-db#25]
Laravel 7 uses Throwable instead of Exception: https://laravel.com/docs/7.x/upgrade#symfony-5-related-upgrades

The column context in the table log is always empty because the method `parseIfException` do not expect Throwable.

**Comment by danielme85** [comment]
Hi, thanks for the info.
I'll see if I can't look for both cases, that would be ideal. Worst case I can start to do major version for major Laravel versions.
I'm still on Laravel 6 on most of my projects but I guess it's about time to give 7 a go ;)

PS: feel free to add a PR, but no pressure!

**Comment by danielme85** [comment]
Hey, wanna be a beta tester @santerref ?
Checkout the "dev-lumen-support" branch and see if that helps with the L7 Throwable.
I was already working on Lumen support but also trying a possible quick Throwable fix at the same time :p

**Comment by danielme85** [comment]
Should be fixed in v2.4.0
169a205b914766f78eec17a54574f2fc4a84fc88
