### ISSUE TITLE
Laravel 6. Serialization of 'Closure' is not allowed

### ISSUE THREAD

**Issue by Aymenel** [danielme85/laravel-log-to-db#26]
Hello. Log entry does not work if there are errors in the view. This leads to an error:

> Serialization of 'Closure' is not allowed {"userId":1,"exception":"[object] (danielme85\\LaravelLogToDB\\Models\\DBLogException(code: 0): Serialization of 'Closure' is not allowed at /home/.../danielme85/laravel-log-to-db/src/LogToDbCustomLoggingHandler.php:70)

**Comment by danielme85** [comment]
Hi, sorry about that!
I think I have a fix for this (to better handle the exception object) in the master branch. 
Are you using the latest release? You could try to see if the master branch works better if you don't mind.

I'll try to get some updates into a new release today, need to do some practical testing first.

**Comment by danielme85** [comment]
Should hopefully work better in release v2.4.0.
a145455e992f52f6528ca495a28967b9044f4707
