### ISSUE TITLE
Slight doc fix

### ISSUE THREAD

**Issue by Sammaye** [danielme85/laravel-log-to-db#3]
In Laravel 5.8, to get a query-able model back from the ext you have to do:
```php
        $logs = LogToDB::model(
            null,
            'mongodb',
            'log'
        )->newModelQuery();
```
Else even though `where()` does not throw an error, it does not seem to do anything either.

**Comment by danielme85** [comment]
Aaaah.... Thanks for the info! I was having issues with this in 5.7 where get() works but all() would fail, this might be why. I’l improve the static “model” function  and do some more testing with 5.8 when I get the chance.

You’re probably better off just creating a simple model in your app and set the same table name as in the logging.php config (default is log). I might make that the recommended way in the readme, at least for now. 

Thanks again @Sammaye!

**Comment by danielme85** [comment]
So turns out: where()->get() works as expected for me. 
MySQL to array.
```php
dd(LogToDB::model()->where('level_name', '=', 'INFO')->get()->toArray());
array:1 [▼
  0 => array:11 [▼
    "id" => 2
    "message" => "this is a info test"
    "channel" => "My DB Log"
    "level" => 200
    "level_name" => "INFO"
    "unix_time" => 1555086034
    "datetime" => DateTime @1555086031 {#337 ▶}
    "context" => null
    "extra" => array:4 [▶]
    "created_at" => "2019-04-12 12:20:34"
    "updated_at" => "2019-04-12 12:20:34"
  ]
]
```

MongoDB to json
```php
dd(LogToDB::model(null, 'mongodb', 'log')->where('level_name', '=', 'DEBUG')->get()->toJson());
[  
   {  
      "id":1,
      "message":"this is a test",
      "channel":"My DB Log",
      "level":100,
      "level_name":"DEBUG",
      "unix_time":1555085980,
      "datetime":{  
         "date":"2019-04-12 12:18:52.910550",
         "timezone_type":3,
         "timezone":"America\/New_York"
      },
      "context":null,
      "extra":{  
         "file":".../src\/Illuminate\/Log\/Logger.php",
         "line":176,
         "class":"Illuminate\\Log\\Logger",
         "function":"writeLog"
      },
      "created_at":"2019-04-12 12:19:40",
      "updated_at":"2019-04-12 12:19:40"
   }
]
```
Getting a new query builder trough newModelQuery() does not change anything in my testing.

There are still lacking model functions, like: all() because Eloquent does not work with dynamically assigned table/collection names.

I've updated the readme I think it might have been a little confusing. 
I would still recommend that you add your own App\Models for both sql and mongoDB. That way all Eloquent functionality should be intact, and you can add relations, mutators etc as you like.

**Comment by danielme85** [comment]
Imma close this. Please reach out if your still having issues.

**Comment by chunterb** [comment]
Hey, sorry for late response - have been very busy.

That did seem to help it though BTW. 

Thanks for this!
