### ISSUE TITLE
Wrong method check

### ISSUE THREAD

**Issue by Manriel** [danielme85/laravel-log-to-db#42]
https://github.com/danielme85/laravel-log-to-db/blob/22853c930818ab4946f9f7cf1693d27740efdc98/src/LogToDB.php#L225

**Comment by danielme85** [comment]
Hey, sorry for the late reply. 
Good catch there: I went back and forth a little. I think getTrace has a closure that breaks the serialization or something like that so changed it to the string version a good while ago.

Thank you, much appreciated! Helps to have an extra set of eyes.

I need to test this whole addon with the newest Laravel as well, been too busy!
