### ISSUE TITLE
getContextAttribute requires a value

### ISSUE THREAD

**Issue by daylightstudio** [danielme85/laravel-log-to-db#46]
Shouldn't `getContextAttribute($value)` and `getExtraAttribute($value)` be something like the following?
```
public function getContextAttribute()
{
     return $this->jsonDecodeIfNotEmpty($this->attributes['context']);
}

public function getExtraAttribute()
{
        return $this->jsonDecodeIfNotEmpty($this->attributes['extra']);
}
```
https://github.com/danielme85/laravel-log-to-db/blob/f3ef48354afef451595d25e0fffc6c5dd882ff9b/src/Models/LogToDbCreateObject.php#L53

**Comment by danielme85** [comment]
I don't think so...?
That's for the setters/mutations I think. 
This be a getter/accesor I believe. 

https://laravel.com/docs/8.x/eloquent-mutators#defining-an-accessor

Is it causing issues?

**Comment by daylightstudio** [comment]
Oh geez. You are right. I alway wrote my getters without the value being passed to it and didn't realize.
