### ISSUE TITLE
Error on Lumen 9.1.2 and PHP 8.1

### ISSUE THREAD

**Issue by iMiodrag** [danielme85/laravel-log-to-db#47]
Lumen v9.1.2
PHP v8.1

Hi there, I am getting the following error when trying to register the service provider in app.php
So after adding: `$app->register(\danielme85\LaravelLogToDB\ServiceProvider::class);`  to `app.php` here is the eror that I am getting:

```
www-data@c2bfa1bae2d0:~/html$ vendor/bin/phpunit 
PHPUnit 9.5.25 #StandWithUkraine

.PHP Fatal error:  Cannot redeclare danielme85\LaravelLogToDB\config_path() (previously declared in /app/vendor/danielme85/laravel-log-to-db/src/ServiceProvider.php:31) in /app/vendor/danielme85/laravel-log-to-db/src/ServiceProvider.php on line 31
PHP Stack trace:
PHP   1. {main}() /app/vendor/bin/phpunit:0
PHP   2. include() /app/vendor/bin/phpunit:123
PHP   3. PHPUnit\TextUI\Command::main($exit = *uninitialized*) /app/vendor/phpunit/phpunit/phpunit:98
PHP   4. PHPUnit\TextUI\Command->run($argv = [0 => 'vendor/bin/phpunit'], $exit = TRUE) /app/vendor/phpunit/phpunit/src/TextUI/Command.php:97
```

**Comment by danielme85** [comment]
Finally, after fighting with my dev/test setup (haven't used it in a little while for this project), I managed to replicate the issue. You are right: there is something iffy with that missing function in Lumen when I try to hack the service provider file to include that config_path call for Lumen. 

I'm gonna do some practical testing for Laravel 9 as well to make sure we are good there, then push a patch soon.

Sorry for the long delay!

**Comment by danielme85** [comment]
This should be fixed on main branch now, I'll make a new release once I see it's all good in practice.
