### ISSUE TITLE
Compatibility with Laravel 10.x and Monolog 3.x

### ISSUE THREAD

**Issue by joostdebruijn** [danielme85/laravel-log-to-db#51]
This package is no longer compatible with Laravel 10.x, which is using Monolog 3.x, causing errors like this:

`Declaration of danielme85\LaravelLogToDB\LogToDbCustomLoggingHandler::write(array $record): void must be compatible with Monolog\Handler\AbstractProcessingHandler::write(Monolog\LogRecord $record): void`

The version constraint `"illuminate/support": ">=5.6"` is suggesting that it is actually compatible, which allows installing this package with Laravel 10.x.

**Comment by danielme85** [comment]
Ah snap, thanks for letting me know!
I see @saulens22 already has a PR to make this work for L10, that's great 👍
So let me set a limit on the current version to monolog 2 and/or L9 and release a new version for Laravel 10 asap.

**Comment by danielme85** [comment]
Should be fixed in v4.0.0, thanks for the tip!
