### ISSUE TITLE
Infinite circular log writes on database exception inside the job

### ISSUE THREAD

**Issue by Manriel** [danielme85/laravel-log-to-db#58]
In case database failure, once the exception rises [inside the job, on attempt to write the log entity to the database](https://github.com/danielme85/laravel-log-to-db/blob/e07c2ab91d96cfad30305dfcce6409882094f983/src/Jobs/SaveNewLogEvent.php#L41), it generates a new log write event, that is pushing to the log queue and attempt to write a new log entity to the database again, that will cause another exception at the same place, and so on.

It immediately cause the water flow cascade effect on the queue, and it's overflow and fail because OOM.

**Comment by danielme85** [comment]
@Manriel I've merged your fix into main branch. I'll tag a new version release after some practical testing. Thanks for your help!

**Comment by danielme85** [comment]
fixed in v4.1.0
