### ISSUE TITLE
Release for Laravel 11

### ISSUE THREAD

**Issue by JGlueck-WIKA** [danielme85/laravel-log-to-db#62]
Hi Daniel, first of all, great work with this package - thanks for that!
Is there a chance to get a release to packagist with the changes you applied a couple of weeks ago to support Laravel 11? By now, the package prevents updating to the latest and greatest. That would be awesome! 🙂

**Comment by danielme85** [comment]
Ah yes, sorry about that. 
I already got some great help from @joostdebruijn to get it ready for L11.
I'm just gonna make a fresh Laravel 11 app and give it a practical run-trough today and make sure its all ok then I'll push a new release.

I appreciate the reminder, I totally forgot :p

**Comment by danielme85** [comment]
Made a new release, im testing fresh installs on Laravel 11 projects. 
Seems like it defaulted to v3 of this package before this release thats no good 🤔 
Lets see if this helps.

**Comment by danielme85** [comment]
This looks better:
```
Running composer update danielme85/laravel-log-to-db
Loading composer repositories with package information
Updating dependencies
Lock file operations: 1 install, 0 updates, 0 removals
  - Locking danielme85/laravel-log-to-db (v4.1.1)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing danielme85/laravel-log-to-db (v4.1.1): Extracting archive
1 package suggestions were added by new dependencies, use `composer suggest` to see details.
Generating optimized autoload files
```

Let me know if it works for ya :)

**Comment by JGlueck-WIKA** [comment]
Legend, works like a charm! Thank you! 😊
