### ISSUE TITLE
Migrate the system from MySQL to MongoDB stop logging

### ISSUE THREAD

**Issue by luismabenitez** [danielme85/laravel-log-to-db#8]

**Comment by danielme85** [comment]
Hi Luis,
sorry for the late reply: I’ve been out of the Laravel/git loop for a little while but I’m back baby!

Could you give me your config/logging.php info so I can try to duplicate?
I’ve never tried to migrate like this, or there might be mongodb specific issues. I usually use sql on my own projects so mongodb is less tested from me in a practical sense. 

I might not have time to look at this until next week. Sorry!

-Dan

**Comment by danielme85** [comment]
im closing this, not heard back. Need env information and config.
